pipeline {
  agent any
  environment {
    NAME = "A-SAMPLE-PIPELINE-01"
  }
  stages {
    stage ('Audit') {
      steps {
        sh '''
          uname -a
        '''
      }
    }
    stage ('Build') {
      steps {
        echo "BUILD ENVIORNOMENT::${env}"
      }
    }
  }
}