pipeline {
    agent {
      node {
        sh '''
           echo $hostname
        '''
      }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}